ESLint changes and changes for deon.
monstercat/declare pull request #5
Opened 2018-04-25 22:09 UTC by Vindexus

Breaking Changes:
 - Process functions are passed an object of key/value pairs instead of `(state, node, ...)`

2018-04-27 18:09 UTC, tmathews requested changes

2018-04-27 18:09 UTC, tmathews commented on core.js
>      opts.data = JSON.stringify(opts.data)
Why leave duplicated logic? You can let this waterfall into the next if which applies the same thing regardless.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +        (done.bind(null, arguments), delay - delta)
What happened to `setTimeout`?

2018-04-27 18:09 UTC, tmathews commented on core.js
> +      withCredentials: true,
This is bad because it does not leave choice.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  if (typeof opts == 'string') {
Avoid allowing multiple typed parameters. Using wrapper methods with appropriate naming is nessary over magical arguments. If this is an artifact from deon, remove this method all together.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +function requestJSON (opts, done) {
I don't like having this as original request method does most of what you need anyways.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  if (opts.data) {
This is handled in request method.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  requestJSON({
Having this here breaks the entire abstraction process by fixating on what can be requested.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  if (!(results instanceof Array)) {
Do not modify parameters. `aResults` is intentional by mindset.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  if (arguments.length == 2) {
Leave intentional parameters.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  if (!matches) {
Revert to old.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  var source = node.dataset.source
:+1:

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  var process
Missing fallback for dummyMethod. Could be potental breakage here. Should also replace dummyMethod with `Function.prototype` if that is intention. Also why declare this here if not modified later?

2018-04-27 18:09 UTC, tmathews commented on core.js
> +    return
This breaks! `results` has to be returned so you can get the array of xhr objects to cancel if need be.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +function loadCache (source, done, reset) {
Why is this needed when we have `requestCached` :no_good_woman:

2018-04-27 18:09 UTC, tmathews commented on forms.js
> +  //Non-form nodes will use our custom code below
Delete this whole file and use a polyfill in your project. Including this piece of code as part of declare misses the point of the project.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +function searchStringToObject () {
:+1:

2018-04-27 18:09 UTC, tmathews commented on core.js
> +function queryStringToObject (str) {
Keep non-mutating params.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +    var target = getTemplate(targetTemplate)
:no_good_woman: You have now bounded core.js and render.js together and they can no longer be used separately. Core should be independent of rendering logic. Will have to rethink this.

2018-04-27 18:09 UTC, tmathews commented on core.js
> +  requestJSON({
Binding specific request logic :no_entry:

2018-04-27 18:09 UTC, tmathews commented on render.js
> +  partials = partials || render.defaultPartials
Keep non-mutating params

2018-04-27 18:09 UTC, tmathews commented on render.js
> +function render (name, el, scope, partials) {
Keep original param order & non-mutating params. Major breakage.

2018-04-27 18:09 UTC, tmathews commented on render.js
> +  loadNodeSources(el)
You must let others choose to do this. Wrapper methods are your friend.

2018-04-27 18:09 UTC, tmathews commented on state.js
> +  const state = aState || {}
Thanks

2018-04-27 18:09 UTC, tmathews commented on state.js
> +  let title
What happened to default?

2018-04-27 18:09 UTC, tmathews commented on state.js
> +    const ev = new CustomEvent("404", {
:+1: Lets use "routenotfound"

2018-04-27 18:09 UTC, tmathews commented on state.js
> +function startState (e) {
I've opted to remove this method all together. Developers should implement their own way to add onPopState in their own DOMContentLoaded listener. `startState` has caused more issues for us than need be.

2018-04-27 19:09 UTC, Vindexus commented on core.js
> +        (done.bind(null, arguments), delay - delta)
No idea. Readded.

2018-04-27 19:21 UTC, Vindexus commented on core.js
> +function loadCache (source, done, reset) {
Honestly just ported this over from old deon because didn't know requestCached existed. I've removed this and replaced loadCached calls with requestCached calls.

2018-04-27 19:22 UTC, Vindexus commented on core.js
> +  requestJSON({
Gone.

2018-04-27 19:22 UTC, Vindexus commented on core.js
> +  if (!(results instanceof Array)) {
👍

2018-04-27 19:24 UTC, Vindexus commented on core.js
> +  if (!(results instanceof Array)) {
Should I be doing cloning for reference parameters? Like `let results = Object.assign({}, results)` for objects or `let results = aResults.slice(0)` for arrays.

2018-04-27 19:24 UTC, Vindexus commented on core.js
> +    return
Fixed.

2018-04-27 22:20 UTC, Vindexus reviewed
Comments.

2018-04-27 22:20 UTC, Vindexus commented on core.js
> +  if (arguments.length == 2) {
👍

2018-04-27 22:20 UTC, Vindexus commented on core.js
> +  if (!matches) {
👍

2018-04-27 22:50 UTC, Vindexus commented on state.js
> +  const state = aState || {}
👍

2018-04-27 22:50 UTC, Vindexus commented on core.js
>      opts.data = JSON.stringify(opts.data)
Removed the logic below.

2018-04-30 22:22 UTC, tmathews requested changes

2018-04-30 22:22 UTC, tmathews commented on core.js
> +                        URL
Wat

2018-04-30 22:22 UTC, tmathews commented on core.js
> -    checkThis = true
Breaking change here.

2018-04-30 22:22 UTC, tmathews commented on core.js
> +    var target = getTemplate(targetTemplate)
Mix of render + core. :no_bell:

2018-04-30 22:22 UTC, tmathews commented on core.js
> +    args.err = err
args.error

2018-04-30 22:22 UTC, tmathews commented on state.js
> +  var el = readState()
Should probably be const.

2018-04-30 22:22 UTC, tmathews commented on state.js
> +    window.dispatchEvent(ev)
why not `window.dispatchEvent(new CustomEvent(...))`

2018-05-01 20:51 UTC, Vindexus commented on core.js
> +    var target = getTemplate(targetTemplate)
Need to find another solution to this then. I use this for when I have multiple parts of the site feeding different sources into one template.

2018-05-01 20:54 UTC, Vindexus commented on core.js
> -    checkThis = true
Did you not ask for this? I must've misread your comment about this. I thought you wanted to remove the variable number of arguments.

2018-05-01 21:15 UTC, Vindexus commented on core.js
> +                        URL
80 char col limit!

2018-05-01 22:03 UTC, tmathews commented on core.js
> +                        URL
No, the only difference in the line is you removed the `*`

2018-05-08 19:06 UTC, Vindexus commented
You should turn on protection against merging without approval on this repo.

2018-05-08 19:56 UTC, tmathews approved these changes

2018-05-08 19:56 UTC, tmathews commented on core.js
> +  var cors = !node.hasAttribute('data-no-cors')
Used once?

2018-05-08 23:23 UTC, merged